aws-solutions/aws-security-hub-automated-response-and-remediation

deployment/testing_requirements.txt

Remove unneeded dependency on bandit

Remove bandit

---

.github/workflows/cdk-nag.yml
.github/workflows/code-style-lint.yml
.github/workflows/codeql.yml
.github/workflows/run-unit-test.yml
.github/workflows/stale-issues.yml

Add linting and testing workflows, stale issues workflow

Add linting and testing workflows, stale issues workflow

---

.github/workflows/cdk-nag.yml

- Use `npm ci` for better repeatability
- Synth all apps

Synth all apps in cdk-nag workflow

---

.github/workflows/code-style-lint.yml
source/playbooks/CIS140/lib/control_runbooks-construct.ts
source/playbooks/SC/lib/control_runbooks-construct.ts
source/playbooks/SC/ssmdocs/SC_EC2.15.ts
source/solution_deploy/lib/remediation_runbook-stack.ts

- Run lint workflow on all branches
- Fix prettier config file
- Use `npm ci` for better reproducibility
- Fix a few style issues

Fix lint workflow

---

source/playbooks/AFSBP/ssmdocs/AFSBP_RDS.2.yaml
source/playbooks/PCI321/ssmdocs/PCI_PCI.RDS.2.yaml
source/playbooks/SC/ssmdocs/descriptions/RDS.2.md
source/remediation_runbooks/DisablePublicAccessToRDSInstance.yaml
source/test/__snapshots__/runbook_stack.test.ts.snap

Added troubleshooting section for PCI RDS.2 as it cannot be performed on a Multi-AZ Cluster.

Added troubleshooting section to PCI RDS.2

---

.gitignore
source/.eslintrc.js

- Add missing eslint config
- Add ignore rule not to ignore eslint config
This should fix the lint workflow. Unit test workflow needs fixing.

Add missing eslint config

---

source/solution_deploy/lib/remediation_runbook-stack.ts
source/test/regex_registry.ts

Fixed formatting of recently added regex_registry unit test and remediation_runbook stack changes. Unit tests pass successfully.

Fixed formatting in regex registry and remediation_runbook stack

---

.gitignore

- clean up outdated gitignore entries

Clean up outdated gitignore entries

---

source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

- fix snapshots that did not get updated when merging

Update snapshots from merge

---

source/solution_deploy/lib/__snapshots__/member-stack.test.ts.snap
source/solution_deploy/lib/cdk-helper/nested-stack.ts
source/solution_deploy/lib/member-stack.test.ts

- part of a larger effort to mitigate rate-limiting issues deploying ssm documents
- add dependencies between each nested stack so they are deployed serially

Serialize nested member stack deployment

---

source/solution_deploy/bin/solution_deploy.ts
source/solution_deploy/lib/__snapshots__/member-stack.test.ts.snap
source/solution_deploy/lib/appregistry/applyAppRegistry.ts
source/solution_deploy/lib/member-stack.test.ts
source/test/__snapshots__/solution_deploy.test.ts.snap

Added AppRegistry application for member stack.
Changed AppRegistry application names to include stack name to allow for multiple in the same account.
Updated unit tests, goes through pipeline successfully, verified manually.

Added AppRegistry application for member stack

---

source/solution_deploy/bin/solution_deploy.ts
source/solution_deploy/lib/__snapshots__/member-stack.test.ts.snap
source/solution_deploy/lib/cdk-helper/nested-stack.ts
source/solution_deploy/lib/member-stack.ts

Added nested member stacks as resource associations in their respective AppRegistry application.
Tested manually. Confirmed that stacks deploy successfully and get associated as expected.

Added nested member stacks to AppRegistry Application

---

source/playbooks/SC/ssmdocs/scripts/check_for_s3_bucket_name.py
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap
source/remediation_runbooks/scripts/PutS3BucketPolicyDeny.py
source/remediation_runbooks/scripts/RemoveLambdaPublicAccess.py
source/remediation_runbooks/scripts/ReplaceCodeBuildClearTextCredentials.py
source/remediation_runbooks/scripts/enable_minor_version_upgrade_rds.py
source/solution_deploy/source/action_target_provider.py
source/test/__snapshots__/runbook_stack.test.ts.snap

Removed more code smells and minor bugs from remediation scripts. This PR will get us below the required threshhold for SonarQube's quality bar for those two categories.
Unit tests pass successfully, solution deploys successfully, and remediation ran successfully in local account.

Removed more code smells/minor bugs from remediation scripts

---

sonar-project.properties
source/LambdaLayers/.coveragerc
source/Orchestrator/.coveragerc
source/playbooks/SC/ssmdocs/scripts/.coveragerc
source/remediation_runbooks/scripts/.coveragerc
source/solution_deploy/source/.coveragerc

This change removes the relative files code coverage config, this was causing most of our tests to go undetected. After this is merged, our corrected code coverage will be back to above 80%.

Fixed undetected tests in code coverage bug

---

source/LambdaLayers/awsapi_cached_client.py
source/LambdaLayers/utils.py
source/Orchestrator/check_ssm_execution.py
source/Orchestrator/exec_ssm_doc.py
source/Orchestrator/get_approval_requirement.py
source/Orchestrator/send_notifications.py
source/Orchestrator/test/test_send_notifications.py
source/lib/runbook_factory.ts
source/playbooks/AFSBP/test/__snapshots__/afsbp_stack.test.ts.snap
source/playbooks/CIS120/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/CIS140/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/NEWPLAYBOOK/test/__snapshots__/newplaybook_stack.test.ts.snap
source/playbooks/PCI321/test/__snapshots__/pci321_stack.test.ts.snap
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap
source/playbooks/common/parse_input.py
source/remediation_runbooks/scripts/PutS3BucketPolicyDeny.py
source/remediation_runbooks/scripts/RevokeUnrotatedKeys.py
source/remediation_runbooks/scripts/disable_publicip_auto_assign.py
source/remediation_runbooks/scripts/enable_minor_version_upgrade_rds.py
source/test/__snapshots__/runbook_stack.test.ts.snap

Fixing a large majority of remaining code smells and lowering code complexity.
Passes all unit tests, ensured that unit tests cover changes (I will try to identify the covering tests in the comments), verified that it spins up successfully, ran one remediation from each runbook successfully.

Fixing more code smells and code complexity

---

source/Orchestrator/check_ssm_execution.py

Moved helper functions outside of main lambda_handler code. Ensured that all variables that get changed are within these helper functions, so they shouldn't be needed in the main function. This is the first story in a series to reduce code complexity on this file. Once merged, this will bring down complexity from 45 to 25.
Passes all unit tests, verified manually that remediations still work and solution is able to be deployed as expected.

Separated out check ssm helper functions to cut code complexity

---

source/Orchestrator/check_ssm_execution.py
source/Orchestrator/test/test_check_ssm_execution.py

Once merged, this script will pass the code complexity quality bar. 
Moved remediation_response logic to its own helper function
- Tested by verifying that unit tests cover this section of code and ensuring that it still passes.
Grouped SSM parameters - Reduced code complexity by 1.
- Added covering unit tests
Deploys successfully, verified that remediations work.

Moved logic to helper function to reduce code complexity

---

source/lib/member-stack.test.ts

- break out first pass over dependencies in member stack test

Break out first pass over dependencies to reduce complexity

---

source/playbooks/AFSBP/test/__snapshots__/afsbp_stack.test.ts.snap
source/playbooks/CIS120/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/CIS140/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/NEWPLAYBOOK/test/__snapshots__/newplaybook_stack.test.ts.snap
source/playbooks/PCI321/test/__snapshots__/pci321_stack.test.ts.snap
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap
source/playbooks/common/parse_input.py
source/playbooks/common/test/test_sc_parse.py

Added support for SC findings in our parse_input script. Added unit test in a similar format to the other standards that we support.
Deploys successfully, passes all unit tests, remediates successfully on test account.

Adding SC support to parse_input script

---

source/lib/member-stack.test.ts

- break out get conditional dependencies from member stack test to reduce complexity

Break out get conditional dependencies to reduce complexity

---

source/lib/remediation_runbook-stack.ts
source/lib/sharrplaybook-construct.ts
source/lib/ssm-doc-rate-limit.ts
source/playbooks/AFSBP/test/__snapshots__/afsbp_stack.test.ts.snap
source/playbooks/CIS120/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/CIS140/lib/cis140_playbook-construct.ts
source/playbooks/CIS140/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/NEWPLAYBOOK/test/__snapshots__/newplaybook_stack.test.ts.snap
source/playbooks/PCI321/test/__snapshots__/pci321_stack.test.ts.snap
source/playbooks/SC/lib/security_controls_playbook-construct.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap
source/test/__snapshots__/runbook_stack.test.ts.snap

- add aspect for rate-limiting ssm docs to each stack

Add aspect for rate-limiting ssm docs

---

source/playbooks/SC/ssmdocs/SC_S3.1.ts
source/playbooks/SC/ssmdocs/SC_S3.2.ts
source/playbooks/SC/ssmdocs/SC_S3.4.ts
source/playbooks/SC/ssmdocs/SC_S3.5.ts
source/playbooks/SC/ssmdocs/SC_S3.6.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

Fix to allow the S3 Security Control remediations to pass.
Deploys successfully and remediation passed.

Manually added RemediationAccount to S3 SC Remediations

---

source/playbooks/CIS140/bin/cis140.ts
source/playbooks/CIS140/lib/control_runbooks-construct.ts
source/playbooks/CIS140/ssmdocs/CIS140_2.2.1.ts
source/playbooks/SC/ssmdocs/SC_CloudTrail.2.ts
source/playbooks/SC/ssmdocs/SC_Config.1.ts
source/playbooks/SC/ssmdocs/SC_EC2.7.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

Some misc fixes for failing SC/CIS 1.4 Remediations.
Tested deploy works successfully and SC remediations pass as expected.

Misc fixes for SC/CIS1.4 Remediations

---

source/playbooks/SC/ssmdocs/SC_CloudWatch.1.ts
source/playbooks/SC/ssmdocs/SC_RDS.4.ts
source/playbooks/SC/ssmdocs/SC_S3.2.ts
source/playbooks/SC/ssmdocs/scripts/sc_get_input_values.py
source/playbooks/SC/ssmdocs/scripts/test/test_sc_get_input_values.py
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

This is a fix for CloudWatch.1-14, S3.2-S3.8, and RDS.4
All remediations have been confirmed working (one from the Cloudwatch and S3 groups), deploys successfully, and passes pipeline successfully.

Squashing more SC Remediation bugs

---

source/remediation_runbooks/scripts/CreateAccessLoggingBucket_createloggingbucket.py
source/remediation_runbooks/scripts/CreateCloudTrailMultiRegionTrail_createcloudtrailbucket.py
source/remediation_runbooks/scripts/CreateCloudTrailMultiRegionTrail_createloggingbucket.py
source/remediation_runbooks/scripts/test/test_createaccessloggingbucket.py
source/remediation_runbooks/scripts/test/test_createcloudtrailmultiregiontrail.py
source/test/__snapshots__/runbook_stack.test.ts.snap

- fail creating buckets if they already exist and are not owned by the remediating account

Fail creating buckets unless they are owned by remediating account

---

source/playbooks/CIS140/bin/cis140.ts
source/playbooks/CIS140/lib/control_runbooks-construct.ts
source/playbooks/CIS140/ssmdocs/CIS140_1.17.ts
source/playbooks/SC/bin/security_controls.ts
source/playbooks/SC/lib/control_runbooks-construct.ts
source/playbooks/SC/ssmdocs/SC_IAM.18.ts
source/playbooks/SC/ssmdocs/descriptions/IAM.18.md
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

Added CIS 1.17 runbook and subsequent SC runbook.
Confirmed working on SC, successful on CIS 1.40. Pipeline successful, deploys successfully.

Added CIS 1.17 Runbook

---

source/remediation_runbooks/scripts/enable_delivery_status_logging.py
source/remediation_runbooks/scripts/test/test_enable_delivery_status_logging.py
source/test/__snapshots__/runbook_stack.test.ts.snap

* Adding all endpoint types
* Fixed test, added error logging to reset
Merging new changes from develop into the release branch

Adding all endpoint types to SNS.2 Remediation (#145)

---

deployment/build-open-source-dist.sh

- build open source dist passes

Removed unused file from open source build script
