aws-solutions/aws-security-hub-automated-response-and-remediation

.github/workflows/run-unit-test.yml

- Install node deps before running unit tests
- Use `npm ci` for better repeatability
- Run workflow on all branches

Install node deps before running unit tests, run on all branches

---

source/Orchestrator/test/test_exec_ssm_doc.py
source/remediation_runbooks/scripts/test/test_createaccessloggingbucket.py
source/remediation_runbooks/scripts/test/test_createcloudtrailmultiregiontrail.py
source/remediation_runbooks/scripts/test/test_replacecodebuildcleartextcredentials.py
source/solution_deploy/source/test/test_action_target_provider.py

- relocate boto calls from module scope to functions so they do not break before stubbed env vars are injected
This should fix the unit test workflow.

Fix import-time problems in unit tests

---

source/jest.config.js
source/package-lock.json
source/package.json
source/playbooks/AFSBP/test/afsbp_stack.test.ts
source/playbooks/CIS120/test/cis_stack.test.ts
source/playbooks/CIS140/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/CIS140/test/cis_stack.test.ts
source/playbooks/NEWPLAYBOOK/test/__snapshots__/newplaybook_stack.test.ts.snap
source/playbooks/NEWPLAYBOOK/test/newplaybook_stack.test.ts
source/playbooks/PCI321/test/pci321_stack.test.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap
source/playbooks/SC/test/security_controls_stack.test.ts
source/test/admin_account_parm.test.ts
source/test/member_stack.test.ts
source/test/orchestrator.test.ts
source/test/orchestrator_logs.test.ts
source/test/runbook_stack.test.ts
source/test/solution_deploy.test.ts
source/test/ssmplaybook.test.ts

- migrate deprecated @aws-cdk/assert to aws-cdk-lib/assertions
- start running snapshot tests for example stack and new stacks

Migrate deprecated @aws-cdk/assert to aws-cdk-lib/assertions

---

source/remediation_runbooks/scripts/RemoveLambdaPublicAccess.py
source/remediation_runbooks/scripts/test/test_removelambdapublicaccess.py
source/test/__snapshots__/runbook_stack.test.ts.snap

- Fixes bug with Lambda.1 Remediation not being able to remove a lambda resource policy pointed at S3 without a SourceAccount.
- Fixes bug with processing of Lambda resource policies that have dicts as principals.
Unit tests pass, new unit test case added, manually tested remediation.

Added Lambda.1 support for removing public S3 resource policies

---

source/Orchestrator/lib/common-orchestrator-construct.ts
source/solution_deploy/bin/solution_deploy.ts
source/solution_deploy/lib/appregistry/applyAppRegistry.ts
source/solution_deploy/lib/solution_deploy-stack.ts
source/test/__snapshots__/orchestrator.test.ts.snap
source/test/__snapshots__/solution_deploy.test.ts.snap
source/test/solution_deploy.test.ts

Changed the population of the nested stacks to be synchronous so it can get passed to our AppRegistry library.
Changed stacks to use NestedStack rather than the L1 construct.
- The L1 construct is still used to populate some requirements for our stacks, but works the same as it did before.

Added nested admin stacks to AppRegistry

---

source/solution_deploy/lib/__snapshots__/member-stack.test.ts.snap
source/solution_deploy/lib/appregistry/applyAppRegistry.ts
source/test/__snapshots__/solution_deploy.test.ts.snap

This change fixes the issue users were having spinning up the templates with a stack name starting with `aws`.

Fixed creation issue with AppRegistry Association Group naming

---

.gitignore
source/tsconfig.json

- emit build results outside of the source tree to avoid clutter
- enable some type-checking compiler options
- upgrade our ES target

Build out of source tree, enable some type-checking options

---

.gitignore
source/jest.config.ts

- convert jest config from js to typescript
- remove ignore rule for config

Convert jest config to typescript

---

deployment/build-s3-dist.sh
source/solution_deploy/source/test/test_wait_provider.py
source/solution_deploy/source/wait_provider.py

- Add custom resource provider for arbitrary wait
This change is to support future changes which will wait between deployments of SSM documents to avoid rate-limiting errors.

Add wait provider

---

buildspec.yml
deployment/build-s3-dist.sh

- don't copy entire source to temp dir
- copy synth-ed json templates rather than re-synth-ing for yaml
- add npm ci to buildspec
This takes the build from ~2m to ~45s. Tested with a deploy of the admin stack.

Speed up build by removing unneeded steps

---

deployment/testing_requirements.txt

- upgrade and unfreeze python testing dependencies - there is no reason to freeze these for local testing
- remove transitive dependency freezes except those frozen to match lambda runtime

Unfreeze testing requirements

---

deployment/build-s3-dist.sh
source/lib/__snapshots__/member-stack.test.ts.snap
source/lib/member-stack.ts
source/lib/remediation_runbook-stack.ts
source/lib/sharrplaybook-construct.ts
source/lib/wait-provider.ts
source/playbooks/AFSBP/test/__snapshots__/afsbp_stack.test.ts.snap
source/playbooks/CIS120/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/CIS140/lib/cis140_playbook-construct.ts
source/playbooks/CIS140/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/NEWPLAYBOOK/test/__snapshots__/newplaybook_stack.test.ts.snap
source/playbooks/PCI321/test/__snapshots__/pci321_stack.test.ts.snap
source/playbooks/SC/lib/security_controls_playbook-construct.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap
source/test/__snapshots__/runbook_stack.test.ts.snap

- add wait provider lambda cdk
- add CFN parameter so wait provider is available in all nested member stacks
Member stack deploys successfully.

Add wait provider lambda cdk

---

CHANGELOG.md
source/lib/__snapshots__/member-stack.test.ts.snap
source/lib/member-stack.ts
source/lib/solution_deploy-stack.ts
source/lib/ssmplaybook.ts
source/solution_deploy/source/test/test_action_target_provider.py
source/test/__snapshots__/solution_deploy.test.ts.snap

Changed custom action name to 'Remediate with ASR' and changed all mentions of Remediate with SHARR.
Overrode logical ids for NestedStacks as the construct will automatically name them to something else. 
Passes all unit tests, deploys on its own and remediates successfully. Also deployed as an update from 1.5.1, it deploys successfully and runs remediations as expected.

Changed Custom Action Name and fixed NestedStack logical IDs

---

source/playbooks/SC/ssmdocs/SC_Redshift.3.ts
source/playbooks/SC/ssmdocs/SC_Redshift.4.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

Corrected name of MinRetentionPeriod parameter and overrode RetentionPeriodSerialized that was missing. This fixes these two Redshift controls.
Deploys successfully, remediations pass.

Fixed missing parameters for Redshift Controls

---

source/lib/remediation_runbook-stack.ts

Theory is that this always failed on AppRegistry stacks, but it was never tested on it. This PR adds the 'servicecatalog:GetApplication' permission to fix it.
Verified working, deploys successfully, passes pipeline.

Added GetApplication permissions to AFSBP CF1

---

CHANGELOG.md
NOTICE.txt
README.md

Updated Readme, changelog, and notice

---

source/lib/__snapshots__/member-stack.test.ts.snap
source/lib/wait-provider.ts
source/solution_deploy/source/wait_provider.py

Changing log level to info to address a security hotspot that came up in SonarQube

Changed wait provider log level to info

---

source/lib/remediation_runbook-stack.ts

Added IAM Perms to CloudFormation.1 remediation to fix issue with nested stacks.
Verified failure before fix, tested and deployed fix, and verified that it succeeded on the same stack.

Added iam:getRole perms to CF1 remediation

---

source/playbooks/SC/lib/security_controls_playbook-construct.ts
source/playbooks/SC/ssmdocs/SC_AutoScaling.1.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

- fix generator ID pattern used by SC auto-trigger EventBridge rules
- fix regex used by SC control runbook to validate AutoScaling group names
With auto-trigger rule enabled, SC AutoScaling.1 remediation triggers and succeeds.

Fix SC rule pattern, fix AutoScaling group name regex

---

source/playbooks/SC/bin/security_controls.ts
source/playbooks/SC/lib/control_runbooks-construct.ts
source/playbooks/SC/ssmdocs/SC_IAM.22.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

Added runbook for SC IAM 22. This is similar to IAM 8 so I am using the same remediation. Because of the 45 day requirement for this remediation, it needs its own runbook so I can pass that parameter along.
Deploys successfully, passes all unit tests, tested by @hearde and successful.

Added runbook for SC IAM 22

---

source/playbooks/SC/bin/security_controls.ts
source/playbooks/SC/ssmdocs/SC_CloudTrail.1.ts
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

Added Cloudtrail.3 as an alternative control for Cloudtrail.1
Deploys successfully, goes through pipeline and passes all unit tests. This remediation still needs to be tested as we cannot get the finding to appear as failed in our accounts.

Added Cloudtrail.3 as an alternative control for Cloudtrail.1

---

source/remediation_runbooks/scripts/enable_delivery_status_logging.py
source/remediation_runbooks/scripts/test/test_enable_delivery_status_logging.py
source/test/__snapshots__/runbook_stack.test.ts.snap

Adding all endpoint types to SNS.2 Remediation, rather than just Lambda. Edited unit testing to reflect this.
Passes all unit tests, deploys successfully, tested and works as expected.

Adding all endpoint types to SNS.2 Remediation

---

source/lib/__snapshots__/ssm-doc-rate-limit.test.ts.snap
source/lib/ssm-doc-rate-limit.test.ts
source/lib/ssm-doc-rate-limit.ts
source/playbooks/AFSBP/test/__snapshots__/afsbp_stack.test.ts.snap
source/playbooks/CIS120/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/CIS140/test/__snapshots__/cis_stack.test.ts.snap
source/playbooks/NEWPLAYBOOK/test/__snapshots__/newplaybook_stack.test.ts.snap
source/playbooks/PCI321/test/__snapshots__/pci321_stack.test.ts.snap
source/playbooks/SC/test/__snapshots__/security_controls_stack.test.ts.snap

- modify doc rate limit aspect to use conditional dependencies if documents are conditional
Tested that modifying the parameters of a nested control runbook stack to disable a document succeeds.

Use conditional dependencies for documents that are conditional

---

source/lib/__snapshots__/member-stack.test.ts.snap
source/package-lock.json
source/package.json
source/test/__snapshots__/solution_deploy.test.ts.snap

- upgrade node dpes
This mitigates the xml2js CVE-2023-0842. Stack update succeeds.

chore: upgrade node deps

---

NOTICE.txt
deployment/testing_requirements.txt
source/lib/remediation_runbook-stack.ts
source/remediation_runbooks/scripts/CreateAccessLoggingBucket_createloggingbucket.py
source/remediation_runbooks/scripts/CreateCloudTrailMultiRegionTrail_createloggingbucket.py
source/remediation_runbooks/scripts/test/test_createaccessloggingbucket.py
source/remediation_runbooks/scripts/test/test_createcloudtrailmultiregiontrail.py
source/test/__snapshots__/runbook_stack.test.ts.snap

- set object writer as bucket ownership property when creating logging buckets

fix: set object writer as bucket ownership property when creating logging buckets

---

sonar-project.properties

- add test.ts to sonar exclusions
This prevents test files from showing as uncovered in our coverage metrics.

chore: add test.ts to sonar exclusions

---

.viperlightignore

- add viperlight ignore for older dependency brought in by moto
Internal pipeline passes.

chore: viperlight ignore dep brought in by moto
